// <auto-generated />
using System;
using Example.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Example.Repository.Migrations
{
    [DbContext(typeof(RegistrationSurveyContext))]
    partial class RegistrationSurveyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Example.Domain.Entities.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("SurveyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyStatus")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("SurveyTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Survey", (string)null);
                });

            modelBuilder.Entity("Example.Domain.Entities.SurveyDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateSurveryDetail")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionScore")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("SurveyId")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("SurveyQuestion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyDetail", (string)null);
                });

            modelBuilder.Entity("Example.Domain.Entities.SurveyDetail", b =>
                {
                    b.HasOne("Example.Domain.Entities.Survey", "Survey")
                        .WithMany("SurveyDetails")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Example.Domain.Entities.Survey", b =>
                {
                    b.Navigation("SurveyDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
